spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/relogio
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect